{"protocolVersion":"0.1.1","runnerVersion":null,"pid":67632,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/Users/sawankumar/AndroidStudioProjects/excelr-mobileapp-flutter/test/widget_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading /Users/sawankumar/AndroidStudioProjects/excelr-mobileapp-flutter/test/widget_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":0}
{"count":1,"time":2,"type":"allSuites"}

[{"event":"test.startedProcess","params":{"observatoryUri":"http://127.0.0.1:54233/yBaRribfaho=/"}}]
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":1724}
{"group":{"id":2,"suiteID":0,"parentID":null,"name":"","metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":1725}
{"test":{"id":3,"name":"Counter increments smoke test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":154,"column":5,"url":"package:flutter_test/src/widget_tester.dart","root_line":14,"root_column":3,"root_url":"file:///Users/sawankumar/AndroidStudioProjects/excelr-mobileapp-flutter/test/widget_test.dart"},"type":"testStart","time":1725}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════\nThe following ProviderNotFoundException was thrown attaching to the render tree:\nError: Could not find the correct Provider<LocalLang> above this MyApp Widget\n\nThis happens because you used a `BuildContext` that does not include the provider\nof your choice. There are a few common scenarios:\n\n- You added a new provider in your `main.dart` and performed a hot-reload.\n  To fix, perform a hot-restart.\n\n- The provider you are trying to read is in a different route.\n\n  Providers are \"scoped\". So if you insert of provider inside a route, then\n  other routes will not be able to access that provider.\n\n- You used a `BuildContext` that is an ancestor of the provider you are trying to read.\n\n  Make sure that MyApp is under your MultiProvider/Provider<LocalLang>.\n  This usually happens when you are creating a provider and trying to read it immediately.\n\n  For example, instead of:\n\n  ```\n  Widget build(BuildContext context) {\n    return Provider<Example>(\n      create: (_) => Example(),\n      // Will throw a ProviderNotFoundError, because `context` is associated\n      // to the widget that is the parent of `Provider<Example>`\n      child: Text(context.watch<Example>().toString()),\n    );\n  }\n  ```\n\n  consider using `builder` like so:\n\n  ```\n  Widget build(BuildContext context) {\n    return Provider<Example>(\n      create: (_) => Example(),\n      // we use `builder` to obtain a new `BuildContext` that has access to the provider\n      builder: (context, child) {\n        // No longer throws\n        return Text(context.watch<Example>().toString());\n      }\n    );\n  }\n  ```\n\nIf none of these solutions work, consider asking for help on StackOverflow:\nhttps://stackoverflow.com/questions/tagged/flutter\n\nWhen the exception was thrown, this was the stack:\n#0      Provider._inheritedElementOf (package:provider/src/provider.dart:343:7)\n#1      Provider.of (package:provider/src/provider.dart:293:30)\n#2      _MyAppState.initState (package:ExcelR/main.dart:57:14)\n#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)\n#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)\n#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)\n#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)\n#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)\n#8      RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1153:5)\n#9      RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1167:7)\n#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)\n#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)\n#12     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1336:19)\n#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)\n#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)\n#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)\n#16     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1185:9)\n#19     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\n#20     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1171:27)\n#21     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:22)\n#24     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\n#25     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:555:27)\n#26     main.<anonymous closure> (file:///Users/sawankumar/AndroidStudioProjects/excelr-mobileapp-flutter/test/widget_test.dart:16:18)\n#27     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)\n<asynchronous suspension>\n<asynchronous suspension>\n(elided 5 frames from dart:async and package:stack_trace)\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":1856}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following TestFailure was thrown running a test:\nExpected: exactly one matching node in the widget tree\n  Actual: _TextFinder:<zero widgets with text \"0\" (ignoring offstage widgets)>\n   Which: means none were found but one was expected\n\nWhen the exception was thrown, this was the stack:\n#4      main.<anonymous closure> (file:///Users/sawankumar/AndroidStudioProjects/excelr-mobileapp-flutter/test/widget_test.dart:19:5)\n<asynchronous suspension>\n<asynchronous suspension>\n(elided one frame from package:stack_trace)\n\nThis was caught by the test expectation on the following line:\n  file:///Users/sawankumar/AndroidStudioProjects/excelr-mobileapp-flutter/test/widget_test.dart line 19\nThe test description was:\n  Counter increments smoke test\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":1858}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following message was thrown:\nMultiple exceptions (2) were detected during the running of the current test, and at least one was\nunexpected.\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":1858}
{"testID":3,"error":"Test failed. See exception logs above.\nThe test description was: Counter increments smoke test","stackTrace":"","isFailure":false,"type":"error","time":1860}
{"testID":3,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":1862}
{"success":false,"type":"done","time":1961}
